# Personal Laptop
[emperor]
species      = "Aptenodytes forsteri"
address      = "100.80.0.1"
architecture = "x86_64-linux"
ed25519      = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILqt+SLcA0kXPLvuF+mogzId9n57rB5y0PyWJ8RE0ja8"
system       = "dell-xps13-9360"


# Oracle VM Flex
[macaroni]
species      = "Eudyptes chrysolophus"
address      = "100.90.0.1"
architecture = "aarch64-linux"
ed25519      = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDs6W94lN0Kx8hOEU4BArPlzkishQGQDVD/gLEsncAzI"
system       = "oracle-vm-a1-flex"
tunnel       = "a972b5e1-8307-4574-a860-c92aaec5adce"


# Oracle VM Micro
[magellanic]
species      = "Spheniscus magellanicus"
address      = "100.90.0.2"
architecture = "x86_64-linux"
ed25519      = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJSd1PUA4w1cne4kg8innCybwHZ1WPGGkNSyQEsJSWt9"
system       = "oracle-vm-e2-1-micro"


# Raspberry Pi
[rockhopper]
species      = "Eudyptes moseleyi"
address      = "100.80.0.3"
architecture = "aarch64-linux"
ed25519      = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDw/Rhr1cdwp3RIwmxTWBa1tWA3gzMyyC8YTJNMN0Fbf"
system       = "raspberry-pi-3b"
