# Dell XPS 13 9360
[emperor]
id = "Aptenodytes forsteri"
architecture = "x86_64-linux"
ed25519 = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILqt+SLcA0kXPLvuF+mogzId9n57rB5y0PyWJ8RE0ja8"


# Dell OptiPlex 3050 Micro
[gentoo]
id = "Pygoscelis papua"
architecture = "x86_64-linux"
ed25519 = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGD2oXkRjJBNZliX+yeki4a/UySHYBR6UvlU1eNnhcXz"


# Oracle VM.Standard.A1.Flex
[macaroni]
id = "Eudyptes chrysolophus"
architecture = "aarch64-linux"
ed25519 = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDs6W94lN0Kx8hOEU4BArPlzkishQGQDVD/gLEsncAzI"


# Raspberry Pi Model 3B+
[rockhopper]
id = "Eudyptes moseleyi"
architecture = "aarch64-linux"
ed25519 = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDw/Rhr1cdwp3RIwmxTWBa1tWA3gzMyyC8YTJNMN0Fbf"
