# Personal Laptop
[emperor]
name         = "emperor"
species      = "Aptenodytes forsteri"
address      = "100.80.0.1"
architecture = "x86_64-linux"
hardware     = "dell-xps13-9360"
impermanent  = true
key          = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILqt+SLcA0kXPLvuF+mogzId9n57rB5y0PyWJ8RE0ja8"


# Home Server
[humboldt]
name         = "humboldt"
species      = "Spheniscus humboldti"
address      = "100.80.0.2"
architecture = "x86_64-linux"
hardware     = "dell-optiplex-3050"
impermanent  = true
key          = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICZDBxFQIZaazAOgPCd9+eLxu7NAg+5a6ZwPmoI2eNGc"


# Oracle VM
[macaroni]
name         = "macaroni"
species      = "Eudyptes chrysolophus"
address      = "100.90.0.1"
architecture = "x86_64-linux"
hardware     = "oracle-vm-e2-1-micro"
impermanent  = false
key          = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDs6W94lN0Kx8hOEU4BArPlzkishQGQDVD/gLEsncAzI"


# Raspberry Pi
[rockhopper]
name         = "rockhopper"
species      = "Eudyptes moseleyi"
address      = "100.80.0.3"
architecture = "aarch64-linux"
hardware     = "raspberry-pi-3b"
impermanent  = false
key          = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDw/Rhr1cdwp3RIwmxTWBa1tWA3gzMyyC8YTJNMN0Fbf"
